"""
Found the clubs in each region manually as there aren't that many, formatted with Google sheets
Current as of 11/01/2024
"""

# regions = [
#     "Seattle", #done
#     "Portland-Vancouver", #done
#     "Northern California", #done
#     "Southern California", #done
#     "Colorado", #done
#     "Texas", #done
#     "Washington D.C.",
#     "Greater NYC",
#     "Florida", #done
# ]


clubs_in_region = {
    "Florida": [
        "Apopka",
        "Homestead",
        "Lake Mary",
        "Doral West",
        "Miami Gardens",
        "Kirkman",
        "Orlando Park Square",
        "Plantation",
        "Winter Park",
    ],
    "Southern California": [
        "Altadena",
        "Anaheim Gateway",
        "Anaheim Hills",
        "Apple Valley",
        "Arcadia",
        "Brea",
        "Buena Park",
        "Burbank Empire",
        "Carlsbad",
        "Carlsbad Palomar Airport",
        "La Costa",
        "Carson",
        "Cerritos",
        "Chino",
        "Chino Hills Marketplace",
        "Bonita",
        "Chula Vista",
        "City of Industry",
        "Puente Hills",
        "Compton",
        "Corona",
        "Costa Mesa",
        "Costa Mesa Newport",
        "South Coast Metro Center",
        "Downey",
        "Eastvale",
        "El Cajon Main St",
        "Escondido La Terraza",
        "Escondido North County Mall",
        "Fontana",
        "Fontana North",
        "Fountain Valley",
        "Fullerton",
        "Garden Grove",
        "Glendale",
        "Glendora",
        "Hawthorne",
        "Hermosa Beach",
        "Hollywood",
        "Huntington Beach Atlanta Ave",
        "Huntington Beach Bella Terra",
        "Huntington Beach Warner Avenue",
        "Indio Jackson Center",
        "Irvine Center Drive",
        "Irvine Marketplace",
        "Rancho San Diego",
        "Ladera Ranch",
        "Laguna Niguel",
        "Ocean Ranch",
        "Foothill Ranch",
        "Lakewood",
        "Lancaster West",
        "Downtown Long Beach",
        "Long Beach",
        "Cypress",
        "La Cienega",
        "Mid Wilshire",
        "Manhattan Beach",
        "Mission Hills",
        "Mission Viejo",
        "Monrovia",
        "Monterey Park",
        "Moreno Valley",
        "North Hollywood",
        "Northridge",
        "Oceanside",
        "Ontario",
        "Orange Chapman",
        "Orange Village",
        "Orangewood",
        "Channel Islands",
        "Oxnard Collection",
        "Panorama City",
        "Pasadena Downtown",
        "Rancho Cucamonga",
        "Rancho Santa Margarita",
        "Redlands",
        "Renaissance Marketplace",
        "Riverside Madison",
        "San Bernardino",
        "San Clemente",
        "Balboa",
        "Carmel Mountain Ranch",
        "College Grove",
        "Imperial Marketplace",
        "Miramar",
        "Mission Valley Center",
        "Navajo",
        "Pacific Beach (San Diego)",
        "Rancho Penasquitos",
        "Stadium",
        "UTC",
        "San Juan Capistrano",
        "Santa Ana",
        "Santa Ana Edinger",
        "Santa Barbara",
        "Santa Fe Springs",
        "Santa Monica",
        "Santee",
        "Sherman Oaks Galleria",
        "Simi Valley",
        "Solana Beach",
        "Thousand Oaks",
        "Torrance",
        "Torrance Del Amo",
        "Upland",
        "Ventura",
        "Walnut",
        "West Covina",
        "West Hills",
        "Whittier",
        "Woodland Hills",
        "Yorba Linda",
    ],
    "Seattle": [
        "Bothell",
        "Issaquah Black Nugget Rd",
        "Panther Lake",
        "Lynnwood",
        "Redmond",
        "Downtown Seattle",
        "Northgate Fifth Ave",
        "Tacoma",
    ],
    "Portland-Vancouver": [
        "Murray Scholls",
        "Tanasbourne",
        "Clackamas",
        "Gladstone",
        "Hillsboro",
        "Downtown Portland",
        "Gresham",
        "Hollywood OR",
        "Portland McLoughlin",
        "The Pearl",
        "Tualatin",
        "Columbia Tech Center",
        "Vancouver 131st Ave",
    ],
    "Northern California": [
        "Antelope Marketplace",
        "Antioch Somersville",
        "Brentwood",
        "Castro Valley",
        "Citrus Heights",
        "El Cerrito",
        "Elk Grove Calvine",
        "Folsom",
        "Fremont Auto Mall",
        "Hayward Amador",
        "Hayward Whipple",
        "Livermore",
        "Millbrae",
        "Milpitas",
        "Moraga Rheem",
        "Mountain View",
        "Newark NewPark Mall",
        "Oakland",
        "Oakland High Street",
        "Pacifica",
        "Petaluma",
        "Pleasanton",
        "Redwood City",
        "Richmond",
        "Rohnert Park",
        "Roseville",
        "West Roseville",
        "Downtown Sacramento",
        "Fulton & Hurley",
        "Laguna",
        "Rancho Cordova",
        "Riverlake",
        "San Carlos",
        "Ocean",
        "Potrero",
        "Sutter-Montgomery",
        "Van Ness",
        "Capitol Expressway",
        "East Side San Jose",
        "Eastridge",
        "Hillsdale",
        "Parkmoor",
        "San Jose",
        "Santa Teresa (San Jose)",
        "Willow Glen",
        "San Leandro",
        "Washington",
        "San Mateo Bovet",
        "San Ramon",
        "Santa Clara",
        "Santa Cruz",
        "Santa Rosa",
        "Sunnyvale Fremont Blvd",
        "Sunnyvale Saratoga",
        "Walnut Creek North Main",
    ],
    "Colorado": [
        "Arvada",
        "Arvada West",
        "North Aurora Chambers",
        "Parker-Arapahoe",
        "North Boulder Iris",
        "Castle Rock",
        "Broadmoor",
        "Alameda Ave (Denver)",
        "Highlands Garden",
        "Lowry",
        "Fort Collins",
        "Centennial",
        "Lafayette",
        "Lakewood",
        "Kipling",
        "South Parker",
    ],
    "Texas": [
        "Arlington",
        "Austin",
        "Hancock Center",
        "Kessler Park",
        "North Dallas",
        "Allen",
        "Fort Worth Horne",
        "Fort Worth Western Center",
        "Lake Worth",
        "Grand Prairie",
        "Copperfield",
        "Dairy Ashford",
        "Galleria",
        "Gulf Freeway",
        "Houston Heights",
        "Houston Rice Village",
        "Voss",
        "Westheimer (Houston)",
        "Willowbrook (Houston)",
        "Valley Ranch",
        "Jacinto",
        "Castle Hills",
        "Mansfield",
        "McKinney",
        "Mesquite",
        "Murphy",
        "Pearland",
        "East Plano",
        "Richardson",
        "Katy Bella Terra",
        "Rockwall",
        "Southlake",
        "Kuykendahl",
        "Spring Energy",
        "Woodlands",
    ],
    "Washington D.C.": ["Fairfax", "Falls Church"],
    "Greater NYC": [
        "Englewood Cliffs",
        "Paramus",
        "Piscataway",
        "Ramsey",
        "Springfield",
        "East Northport",
        "Kew Gardens",
        "Nanuet",
        "Pelham Manor",
        "Scarsdale",
        "Valley Stream Green Acres",
        "Yorktown Heights",
    ],
}


"""
find the best-priced gym that gets me access to the UTC location
     find the best-priced national plan out of all the U.S. locations at each commitment level
     find the best-priced regional plan out of all the Southern California locations

prices: 
    price (default selected): <div _ngcontent-oei-c87="" class="price-content"><!----><sup _ngcontent-oei-c87="" class="dollar selected"> $ </sup><label _ngcontent-oei-c87="" class="price selected"> 27.99 </label><sub _ngcontent-oei-c87="" aria-hidden="true" class="month selected"> /mo </sub><sub _ngcontent-oei-c87="" class="month ada-per-month selected"> per month </sub><!----><!----><!----></div>
    other prices: <div _ngcontent-oei-c87="" class="price-content"><!----><sup _ngcontent-oei-c87="" class="dollar"> $ </sup><label _ngcontent-oei-c87="" class="price"> 48.99 </label><!----><!----><!----><sub _ngcontent-oei-c87="" aria-hidden="true" class="month"> /mo</sub><sub _ngcontent-oei-c87="" class="month ada-per-month"> per month</sub><!----><!----><!----><!----></div>

    
National, Platinum, Gold, Silver:

<div _ngcontent-oei-c92="" class="title" data-slnm-id="title-New National">National</div>
<div _ngcontent-oei-c92="" class="title" data-slnm-id="title-National">Platinum</div>
<div _ngcontent-oei-c92="" class="title" data-slnm-id="title-Regional">Gold</div>


Yearly, Monthly: <div _ngcontent-oei-c83="" data-slnm-id="cardHeaderTitle" class="title">Yearly</div>

12-Mo Commitment: <div _ngcontent-oei-c83="" data-slnm-id="cardHeaderSubTitle" class="sub-title">12 Mo Commitment</div>

"""
